const HTTP_SUCCESS_CODE = 200;
const HTTP_CREATED_CODE = 201;
const HTTP_BAD_REQUEST_CODE = 400;
const HTTP_UNAUTHORIZE_CODE = 401;
const HTTP_FORBIDDEN_CODE = 403;
const HTTP_NOT_FOUND_CODE = 404;
const HTTP_CONFLICT_CODE = 409;
const HTTP_FAILURE_CODE = 500;

const JWT_TOKEN_SECRET = 'my-32-character-ultra-secure1234';
const JWT_TOKEN_LIFETIME = '300m';

module.exports = {
    HTTP_SUCCESS_CODE,
    HTTP_CREATED_CODE,
    HTTP_BAD_REQUEST_CODE,
    HTTP_UNAUTHORIZE_CODE,
    HTTP_FORBIDDEN_CODE,
    HTTP_NOT_FOUND_CODE,
    HTTP_CONFLICT_CODE,
    HTTP_FAILURE_CODE,
    JWT_TOKEN_SECRET,
    JWT_TOKEN_LIFETIME,
};
